Repository FRONTENDSCHOOLPLUS2/hyundai-morgans, pull requests merged in 2024-08, with the labels that each got.

#13 💄style: 메인페이지 퍼블리싱
  jjtest_push.txt
  public/fonts/HYUNDAI.TTF
  public/fonts/hyundai-sans/HyundaiSansHeadOffice-Bold.woff2
  public/fonts/hyundai-sans/HyundaiSansHeadOffice-Light.woff2
  public/fonts/hyundai-sans/HyundaiSansHeadOffice-Medium.woff2
  public/fonts/hyundai-sans/HyundaiSansHeadOffice-Regular.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-Bold.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-BoldItalic.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-Italic.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-Medium.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-MediumItalic.woff2
  public/fonts/hyundai-sans/HyundaiSansTextOffice-Regular.woff2
  public/fonts/pretendard/Pretendard-Black.woff2
  public/fonts/pretendard/Pretendard-Bold.woff2
  public/fonts/pretendard/Pretendard-ExtraBold.woff2
  public/fonts/pretendard/Pretendard-ExtraLight.woff2
  public/fonts/pretendard/Pretendard-Light.woff2
  public/fonts/pretendard/Pretendard-Medium.woff2
  public/fonts/pretendard/Pretendard-Regular.woff2
  public/fonts/pretendard/Pretendard-SemiBold.woff2
  public/fonts/pretendard/Pretendard-Thin.woff2
  public/images/btn_next.png
  public/images/btn_prev.png
  public/images/ev3_bg.png
  public/images/ev4_bg.png
  public/images/ev5_bg.png
  public/images/g70.png
  public/images/genisisu_logo_b.png
  public/images/genisisu_logo_w.png
  public/images/menu_ham.png
  src/app/css/basic.css
  src/app/css/fonts.css
  src/app/css/globals.css
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 🎨스타일

#15 🐛fix: 메인페이지 퍼블리싱 수정
  src/app/css/basic.css
  src/app/page.tsx
  src/components/layout/Footer.tsx
Labels: 🪲버그 수정, 🎨스타일

#16 🐛fix: 메인페이지 2차 퍼블리싱 수정
  src/app/css/basic.css
  src/app/page.tsx
Labels: 🎨스타일

#19 :sparkles: feat:#5 product fetch 구현
  env.d.ts
  genisisu/bruno.json
  genisisu/collection.bru
  genisisu/environments/genisisu_env.bru
  genisisu/상품 목록 조회.bru
  public/images/favicon-white.ico
  src/app/(community)/[type]/list/Order/page.tsx
  src/app/(community)/[type]/list/page.tsx
  src/app/(community)/[type]/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/layout/Header.tsx
  src/data/fetch/model.ts
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
  src/types/product.ts
Labels: 🧵기능 추가

#21 💄style:#17 상품목록페이지 퍼블리싱 완료
  src/app/(g-items)/itemlist/page.tsx
  tailwind.config.ts
Labels: 🎨스타일

#20 :sparkles: feat: #18 Model List 페이지 기능 구현
  public/images/genesis-kr-gv70-facelift-sport-glossy-colors-uyuni-white-large.png
  src/app/(community)/[type]/list/ModelCard.tsx
  src/app/(community)/[type]/list/page.tsx
  src/components/layout/Header.tsx
Labels: 🧵기능 추가

#22 :sparkles: feat: #18 상품 목록 UI 적용
  genisisu/관리자 로그인.bru
  genisisu/셀러 로그인.bru
  src/app/(community)/[type]/list/ModelCard.tsx
  src/app/(community)/[type]/list/page.tsx
  src/app/(g-items)/itemlist/page.tsx
  src/data/fetch/productFetch.ts
  src/types/product.ts
Labels: 🧵기능 추가, 🎨스타일

#23 :bug: fix: 상품 목록에서 옵션항목 숨기기
  src/app/(community)/[type]/list/ModelCard.tsx
  src/app/(community)/[type]/list/page.tsx
  src/app/(g-items)/itemlist/page.tsx
  src/components/layout/Header.tsx
Labels: 🪲버그 수정

#26 :truck: rename: #5 폴더 구조 및 이름 변경
  src/app/(web)/(user)/login/LoginForm.tsx
  src/app/(web)/(user)/login/page.tsx
  src/app/(web)/(user)/signup/SignupForm.tsx
  src/app/(web)/(user)/signup/page.tsx
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/(web)/models/page.tsx
  src/components/layout/Header.tsx
Labels: 🧻이름 재설정

#32 :bug:fix:#31 header컴포넌트 긴급수정
  src/components/layout/Header.tsx
  src/components/layout/HeaderChild.tsx
Labels: :bug: 버그 수정

#33 ♻️ refactor: #5 header 컴포넌트 수정
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/css/basic.css
  src/app/layout.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderChild.tsx
  src/components/layout/HeaderMain.tsx
Labels: ♻️리팩토링

#37 :lipstick: style: #36 파비콘 추가
  genisisu/environments/genisisu_env.bru
  genisisu/게시물 목록 조회.bru
  public/images/favicon.svg
  src/app/(web)/[boards]/page.tsx
  src/data/fetch/postFetch.ts
  문서작성 및 업데이트
Labels: :lipstick: 스타일

#39 :spakles: feat: #5 view360 기능 추가
  package-lock.json
  package.json
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/css/basic.css
  src/components/layout/Header.tsx
  src/data/fetch/productFetch.ts
  src/types/product.ts
Labels: 💎기능 추가

#40 :lipstick:style 상세페이지 퍼블리싱 수정 및 PR 충돌 수정
  public/images/detail/defaultCar.png
  public/images/detail/genesis_detail_360samp01.jpg
  public/images/detail/innerDesign.jpg
  public/images/detail/outerDesign.jpg
  public/images/detail/spec_1.png
  public/images/detail/spec_2.png
  public/images/detail/spec_2_1.png
  public/images/detail/spec_2_2.png
  public/images/detail/spec_2_3.png
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ModelGnb.tsx
  src/app/(web)/models/[model]/ModelLnb.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/css/basic.css
  tailwind.config.ts
  tsconfig.json
Labels: :bug: 버그 수정, :lipstick: 스타일

#41 ✨ feat: 상품 목록에서 모델별 주문하기로 이동 #7
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/page.tsx
  src/data/fetch/productFetch.ts
Labels: 💎기능 추가

#42 💄style: 상세페이지 퍼블리싱 및 결제안내 페이지 퍼블리싱
  public/images/detail/optionSamp.png
  src/app/(web)/models/[model]/ModelGnb.tsx
  src/app/(web)/models/[model]/ModelLnb.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/css/basic.css
Labels: :lipstick: 스타일

#43 :spakles: feat: #7 모델 옵션 LNB 기능 구현
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/ModelLnb.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
Labels: 💎기능 추가

#46 :seedling: add: prettierrc 추가
  .eslintrc.json
  .prettierrc
  src/app/css/globals.css
Labels: 📂파일 추가

#48 :sparkles: feature: #6 명칭 클릭 시 text-white 속성 제어
  genisisu/게시물 상세 조회.bru
  package-lock.json
  package.json
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/ModelGnb.tsx
  src/app/(web)/models/[model]/ModelLnb.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
  src/data/fetch/productFetch.ts
  src/types/product.ts
  src/zustand/useModel.ts
  src/zustand/usePostItem.js
  src/zustand/useProfile.js
Labels: 💎기능 추가

#49 :bug:fix: 전시시승 게시판 CSS & UI 수정 및 기능 수정하기
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/ModelGnb.tsx
  src/app/(web)/models/[model]/ModelLnb.tsx
  src/app/(web)/models/[model]/page.tsx
  src/components/Button.tsx
  src/components/Pagination.tsx
  src/components/Search.tsx
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
  src/types/post.ts
  src/types/user.ts
Labels: 💎기능 추가, :bug: 버그 수정, :lipstick: 스타일, /* 주석 추가 */, 🔑 API 수정

#54 ✨feat: bruno 댓글 컬렉션 추가
  genisisu/collection.bru
  genisisu/environments/genisisu_env.bru
  genisisu/게시물/게시물 목록 조회.bru
  genisisu/게시물/게시물 상세 조회.bru
  genisisu/게시물/댓글/댓글 등록.bru
  genisisu/게시물/댓글/댓글 목록 조회.bru
  genisisu/게시물/댓글/댓글 삭제.bru
  genisisu/게시물/댓글/댓글 수정.bru
  genisisu/상품/개별 상품 목록 조회.bru
  genisisu/상품/상품 목록 조회.bru
  genisisu/회원/관리자 로그인.bru
  genisisu/회원/셀러 로그인.bru
  src/app/(web)/models/[model]/ImageViewer.tsx
Labels: 💎기능 추가, 📂파일 추가

#55 :sparkles:feat:#45 메인페이지 스크롤링 인터렉션
  jjtest_push.txt
  src/app/(event_component)/MainPagenation.tsx
  src/app/css/basic.css
  src/app/page.tsx
Labels: 💎기능 추가

#56 💄style: #50 전시시승 댓글 창 스타일 변경
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/page.tsx
  src/components/Button.tsx
Labels: :lipstick: 스타일

#57 :sparkles: feat: #6 상품 상세 도색 변경 기능 추가
  src/app/(web)/models/[model]/ModelColor.tsx
  src/types/product.ts
Labels: 💎기능 추가, 🔑 API 수정, 📂파일 추가

#60 🐛fix: 로그인 & 회원가입 이동 버그 추가
  src/app/(web)/[boards]/new/page.tsx
  src/components/layout/Header.tsx
Labels: :bug: 버그 수정

#61 ✨feat:#45 메인페이지 인터렉션 작업 (상단타이틀, 캐러셀)
  public/images/ev4_bg_02.jpg
  public/images/ev4_bg_02.png
  public/images/ev4_bg_03.jpg
  public/images/ev4_bg_04.jpg
  public/images/g90.png
  src/app/css/basic.css
  src/app/page.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event4.tsx
  src/components/mainPageComponents/MainPagenation.tsx
Labels: 💎기능 추가, :lipstick: 스타일

#63 :bug: fix: #6 상품 목록과 상품 상세 페이지가 안들어가지는 이슈 해결
  src/app/(web)/models/ModelCard.tsx
  src/data/fetch/productFetch.ts
  src/zustand/useModel.ts
Labels: :bug: 버그 수정

#64 :bulb: comment: prettier 설정 추가
  .eslintrc.json
  .prettierrc
Labels: :bug: 버그 수정

#66 💄style: #50 전시시승 댓글 창 텍스트 컬러 변경
  src/app/(web)/[boards]/[id]/CommentNew.tsx
Labels: :lipstick: 스타일

#68 :bug:fix:#67 메인페이지 캐러셀 오류 수정
  src/app/(web)/models/[model]/page.tsx
  src/app/page.tsx
  src/components/mainPageComponents/Event2.tsx
Labels: :bug: 버그 수정

#69 ✨feat: #51 전시시승 댓글 작성 기능 구현 및 스타일 수정
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/data/actions/postAction.ts
  src/data/fetch/postFetch.ts
Labels: 💎기능 추가, :lipstick: 스타일

#71 :truck:rename:#70 협업을 위한 메인페이지 컴포넌트 분할
  src/app/page.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event5.tsx
Labels: 🕶️ 이름 재설정

#73 :sparkles: feat: #6 fetchVehicles 함수 추가
  genisisu/상품/상품 검색(extra 속성으로 검색, 오름차순).bru
  genisisu/상품/상품 정렬(_id 오름차순).bru
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/page.tsx
  src/data/fetch/productFetch.ts
Labels: 💎기능 추가

#77 ✨feat: #74 게시물 작성 페이지 스타일 CSS 변경 및 취소 버튼 누르면 전시시승 목록 페이지로 이동 구현
  src/app/(web)/[boards]/new/page.tsx
Labels: 💎기능 추가, :lipstick: 스타일

#78 :bug: fix: Option fetch 함수 수정
  genisisu/상품/상품 검색(extra 속성으로 검색) caterogry.bru
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/page.tsx
  src/data/fetch/postFetch.ts
  src/data/fetch/productFetch.ts
Labels: :bug: 버그 수정

#79 ✨feat: #74 게시물 작성 기능 구현
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/data/actions/postAction.ts
Labels: 💎기능 추가, :lipstick: 스타일

#80 :bug:fix:#67 타입에러 수정
  src/app/page.tsx
  src/components/mainPageComponents/Event2.tsx
Labels: :bug: 버그 수정

#82 🐛 fix:#67 메인페이지 타입에러 수정(3rd)
  src/components/mainPageComponents/MainPagenation.tsx
Labels: :bug: 버그 수정

#88 ✨feat: #75 전시시승 게시물 수정 브루노 세팅 완료
  genisisu/environments/genisisu_env.bru
  genisisu/게시물/게시물 상세 조회.bru
  genisisu/게시물/게시물 수정.bru
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/page.tsx
Labels: 💎기능 추가

#90 :sparkles: #6 모델 상세 페이지 구현(g90-black)
  .prettierrc
  src/app/(web)/models/[model]/ImageViewer.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/Section1Index.tsx
  src/app/(web)/models/[model]/Section2Intro.tsx
  src/app/(web)/models/[model]/Section3Color.tsx
  src/app/(web)/models/[model]/Section4Exterior.tsx
  src/app/(web)/models/[model]/Section5Interior.tsx
  src/app/(web)/models/[model]/Section6Spec.tsx
  src/app/(web)/models/[model]/layout.tsx
  src/app/(web)/models/[model]/page.tsx
  src/app/(web)/models/page.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/navigation/ModelGnb.tsx
  src/components/navigation/ModelLnb.tsx
  src/types/product.ts
  src/zustand/useModel.ts
Labels: 💎기능 추가

#91 💄style: #89 전시시승 체험 신청 게시판 퍼블리싱 작업
  src/app/(web)/[boards]/drive/page.tsx
  src/app/css/basic.css
  src/components/Button.tsx
  tsconfig.json
Labels: :lipstick: 스타일, 📂파일 추가

#93 💄style: #89 페이지 하단 테이블 코딩 완료
  public/images/detail/btn_drop.png
  src/app/(web)/[boards]/drive/page.tsx
  src/app/css/customSelect.css
  src/components/Button.tsx
Labels: :lipstick: 스타일

#97 :sparkles: feat: #6 버튼 페이지 라우팅 기능 추가
  src/app/(web)/models/ModelCard.tsx
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/(section)/Section2Intro.tsx
  src/app/(web)/models/[model]/(section)/Section3Color.tsx
  src/app/(web)/models/[model]/(section)/Section4Exterior.tsx
  src/app/(web)/models/[model]/(section)/Section5Interior.tsx
  src/app/(web)/models/[model]/(section)/Section6Spec.tsx
  src/app/(web)/models/[model]/Section1Index.tsx
  src/app/(web)/models/[model]/Section3Color.tsx
  src/app/(web)/models/[model]/[option]/(layout)/Layout1Basic.tsx
  src/app/(web)/models/[model]/[option]/(layout)/Layout2Color.tsx
  src/app/(web)/models/[model]/[option]/(layout)/Layout3Center.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/page.tsx
  src/components/Button.tsx
  src/components/navigation/ModelLnb.tsx
  src/data/extractTitle.ts
  src/hook/useLocalStorage.ts
  src/types/product.ts
  src/zustand/useModel.ts
Labels: 💎기능 추가, :bug: 버그 수정

#98 ✨feat: #74 merge 완료
  src/app/(web)/[boards]/drive/page.tsx
  src/data/actions/postAction.ts
Labels: :bug: 버그 수정

#95 💄style: #89 전시시승 신청 페이지 퍼블리싱 완료
  public/images/btn_drop_icon.png
  src/app/(web)/[boards]/drive/page.tsx
  src/app/css/customSelect.css
  src/data/actions/postAction.ts
Labels: :lipstick: 스타일

#94 :sparkles:feat:#83 상세페이지 subGNB 개발
  package-lock.json
  package.json
  src/app/css/basic.css
  src/components/mainPageComponents/Event2.tsx
  src/components/navigation/ModelGnb.tsx
Labels: 💎기능 추가

#102 :bug: fix: 데이터 구조 변경에 따른 타입 수정
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/data/fetch/productFetch.ts
  src/types/product.ts
  tsconfig.json
Labels: :bug: 버그 수정

#101 ✨feat:#99 메인페이지 캐러셀 이벤트 -> swiper 라이브러리 변경
  src/app/css/basic.css
  src/components/mainPageComponents/Event2.tsx
  src/components/mainPageComponents/Event4.tsx
Labels: 💎기능 추가, ♻️리팩토링

#104 ✨feat:#100 메인페이지 siteMap 수정
  src/app/css/basic.css
  src/components/layout/Header.tsx
  src/components/mainPageComponents/Event2.tsx
Labels: 💎기능 추가, :lipstick: 스타일

#105 ✨feat: #74 전시시승 게시물 작성 (서브페이지) 개발기능구현 완료
  .vscode/settings.json
  genisisu/environments/genisisu_env.bru
  genisisu/게시물/게시물 등록.bru
  genisisu/게시물/게시물 상세 조회.bru
  genisisu/전시시승/게시물 등록.bru
  genisisu/전시시승/게시물 목록 조회.bru
  genisisu/전시시승/게시물 삭제.bru
  genisisu/전시시승/게시물 상세 조회.bru
  genisisu/전시시승/게시물 수정.bru
  genisisu/전시시승/댓글/댓글 등록.bru
  genisisu/전시시승/댓글/댓글 목록 조회.bru
  genisisu/전시시승/댓글/댓글 삭제.bru
  genisisu/전시시승/댓글/댓글 수정.bru
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/drive/page.tsx
  src/app/(web)/[boards]/new/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/components/Pagination.tsx
  src/components/Pagination2.tsx
  src/components/Search.tsx
  src/data/actions/postAction.ts
  src/data/fetch/postFetch.ts
  src/types/post.ts
Labels: 💎기능 추가, :lipstick: 스타일

#109 :sparkles: feat: #103 엔진, 구동, 휠 옵션 페이지 구현
  genisisu/상품/상품 검색(extra 속성으로 검색) caterogry.bru
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/ModelColor.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/page.tsx
  src/data/fetch/productFetch.ts
  src/types/product.ts
Labels: 💎기능 추가, 🔑 API 수정

#111 ♻️refactor: 전시시승 신청 게시판 컴포넌트 분리
  .vscode/settings.json
  src/app/(web)/[boards]/drive/page.tsx
  src/components/drive/AddBoard.tsx
  src/components/mainPageComponents/Event5.tsx
  src/data/actions/postAction.ts
Labels: ♻️리팩토링, 📂파일 추가

#112 🐛 fix:#107 메인페이지 event5 퍼블리싱 수정
  src/app/css/basic.css
  src/components/drive/AddBoard.tsx
Labels: :bug: 버그 수정

#114 ✨feat: #75 수정기능 버튼 스타일 수정 및 일부 코드 수정
  src/app/(web)/[boards]/[id]/edit/page.tsx
  src/app/(web)/[boards]/[id]/editDrive/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/data/actions/postAction.ts
Labels: 💎기능 추가, :lipstick: 스타일

#116 ✨feat: #113 게시물 삭제 코드 일부 수정 및 스타일 변경
  src/app/(web)/[boards]/[id]/page.tsx
  src/data/actions/postAction.ts
Labels: 💎기능 추가, :lipstick: 스타일

#117 🐛 fix:#75 site map 퍼블리싱 이슈 수정
  src/app/css/basic.css
Labels: :lipstick: 스타일

#118 :lipstick:style: #106 상세페이지 스타일링 작업
  src/app/(web)/[boards]/[id]/page.tsx
Labels: :lipstick: 스타일

#120 :bug: fix: localStorage 알수 없음 에러 수정
  src/app/(web)/models/ModelCard.tsx
  src/hook/useLocalStorage.ts
Labels: :bug: 버그 수정

#121 :recycle:refactor: #72 메인 전시시승 신청 코드 컴포넌트 분리 및 스타일링
  src/app/css/basic.css
  src/components/drive/AddBoard.tsx
Labels: :lipstick: 스타일, ♻️리팩토링

#122 :bug:fix: Merge branch feature/#75
  src/app/(web)/[boards]/[id]/editDrive/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/components/drive/AddBoard.tsx
Labels: :bug: 버그 수정

#123 :ambulance:hotfix: #74 게시물 작성시 스크롤 최상단으로 이동되게 코드 수정
  src/app/(web)/[boards]/ScrollToTop.ts
  src/app/(web)/[boards]/page.tsx
  src/data/actions/postAction.ts
Labels: :bug: 버그 수정, 📂파일 추가

#124 :sparkles: feat: Merge를 위해 커밋
  genisisu/상품/상품 검색(extra 속성으로 검색) caterogry.bru
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/components/layout/Footer.tsx
  src/components/navigation/ModelLnb.tsx
Labels: 🕶️ 이름 재설정

#126 :bulb: fix: 상품 리스트 전시시승 작성 링크 수정
  src/app/(web)/models/ModelCard.tsx
Labels: 🕶️ 이름 재설정

#129 :ambulance: hotfix: 로컬 스토리지 저장 안되는 문제 해결
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/zustand/useModel.ts
Labels: :bug: 버그 수정

#130 :sparkles:feat: #127 qna(고객지원) 게시판 게시물 등록 페이지 변수 설정 및 기능개발
  src/app/(web)/[boards]/drive/page.tsx
  src/components/drive/AddBoard.tsx
  src/data/fetch/postFetch.ts
Labels: 💎기능 추가, ♻️리팩토링

#131 💄style:#128 메인페이지 및 게시판페이지 퍼블리싱 수정
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/editDrive/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/drive/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/ModelCard.tsx
  src/app/css/basic.css
  src/components/layout/Header.tsx
  src/components/mainPageComponents/MainPagenation.tsx
Labels: :lipstick: 스타일, ♻️리팩토링

#132 ✨feat: qna, 공지사항 게시판 기능개발 완료
  genisisu/전시시승/게시물 조회.bru
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/editDrive/page.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/drive/page.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/page.tsx
  src/components/Pagination.tsx
  src/components/drive/AddBoard.tsx
  src/components/mainPageComponents/Event5.tsx
  src/data/actions/postAction.ts
Labels: 💎기능 추가, :bug: 버그 수정, :lipstick: 스타일

#133 :ambulance:hotfix: #89 게시판 오류 수정
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/[id]/CommentItem.tsx
  src/app/(web)/[boards]/[id]/CommentList.tsx
  src/app/(web)/[boards]/[id]/CommentNew.tsx
  src/app/(web)/[boards]/[id]/page.tsx
  src/app/(web)/[boards]/drive/page.tsx
  src/app/(web)/[boards]/page.tsx
Labels: 💎기능 추가, :bug: 버그 수정, :lipstick: 스타일, ♻️리팩토링

#134 ✨feat: 배포를 위한 머지 수정
  public/images/btn_next_b.png
  public/images/warning.png
  src/app/(web)/models/[model]/(section)/Section1Index.tsx
  src/app/(web)/models/[model]/[option]/(layout)/ColorLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/HorizontalLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/OptionReadyLayout.tsx
  src/app/(web)/models/[model]/[option]/(layout)/VerticalLayout.tsx
  src/app/(web)/models/[model]/[option]/page.tsx
  src/app/(web)/models/[model]/payments/PaymentsAction.tsx
  src/app/(web)/models/[model]/payments/page.tsx
  src/app/(web)/models/[model]/payments/paymentsComplete/page.tsx
  src/app/(web)/models/paymentsComplete/page.tsx
  src/app/css/basic.css
  src/app/error.tsx
  src/app/not-found.tsx
  src/components/drive/AddBoard.tsx
  src/components/mainPageComponents/Event2.tsx
  src/components/navigation/ModelLnb.tsx
Labels: :lipstick: 스타일, ♻️리팩토링

#135 🐛fix:#128 메인페이지 퍼블리싱 수정
  src/app/css/basic.css
  src/components/drive/AddBoard.tsx
Labels: :lipstick: 스타일

#136 :bug: fix: #89 배포판에서 게시물 작성 오류
  src/components/drive/AddBoard.tsx
  src/data/actions/postAction.ts
Labels: :bug: 버그 수정

#138 :ambulance: hotfix: 메인 alert, 게시판 라우팅 기능, 옵션 가격 수정
  src/app/(web)/[boards]/ListItem.tsx
  src/app/(web)/[boards]/page.tsx
  src/app/(web)/models/[model]/[option]/(layout)/OptionReadyLayout.tsx
  src/components/mainPageComponents/Event1.tsx
  src/components/mainPageComponents/Event3.tsx
  src/components/mainPageComponents/Event4.tsx
  src/data/actions/postAction.ts
Labels: :bug: 버그 수정
